# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f87575c9c2e7813128a8bcdbd76f969079d11091c733baa9fa4222f705075400e6996e997978893681fc7e9af24ad64d19c963c5ffa9b0765950b22f3eaf5491

test:
  secret_key_base: 919788ceaf75ef1122b17a91eed71cfdca06f6d05b286d5b06e589519dc028ac6613d61dd86e983a0e9cb029d1b556c49943859f0f1e6851c94755df27547a8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
